# Server
server.port=8000
server.servlet.context-path=/api

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/nextkart_auth_db
spring.datasource.username=postgres
spring.datasource.password=Debjit@2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=debjitpal46@gmail.com
spring.mail.password=ajbejnoeuozuiieb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# JWT Configuration
jwt.secret=0e58d7101366a842946341384cd5c090625bf5e9b7cb82859192f26d69094965
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Application
spring.application.name=nexkart-auth
logging.level.root=INFO
logging.level.com.debjit.nexkart_auth=DEBUG